### ISSUE TITLE
Option to use [External] and extern

### ISSUE THREAD

**Issue by geoffreymcgill** [mint-nx/mint-Bridge#1]
Another option for configuring the `mint.console` class would be using `[External]` attribute and `extern` modifier on the members. This technique would remove the dependency on maintaining strings in the `Script.Call` statements. 

The following sample demonstrates another option for [Global.cs](https://github.com/mint-nx/mint-Bridge/blob/master/mint-Bridge/console/Global.cs):

https://deck.net/e0a971944ebc68aabd0b62890e7f8d30

```csharp
namespace mint
{
    [External]
    public static class console
    {
        public extern static void init();
        public extern static void exit();
        public extern static void clear();
        public extern static void print(string Contents = "");
        public extern static void println(string Contents = "");
    }
}
```

Just another option and something to think about. 

Hope this helps.

**Comment by XorTroll** [comment]
Oh, interesting... So that way the Script.Call(...) wouldn't be necessary and Bridge would auto-guess it?
Even "namespaces", as the JS libs are "mint.console.println(...)"?

Amazing!

**Comment by geoffreymcgill** [comment]
> and Bridge would auto-guess it

It's more of an assumption. By applying `[External]` you're stating that all the actual runtime implementation is _handled externally_ and you just want Bridge to generate the function calls based on the defined namespace.class.method pattern. 

In your case, I'm assuming there's a **mint.js** file that is loaded into the .html file after **bridge.js**?

Bridge provides a lot of configurable options for mapping the C# to your ideal JS implementation. Please see the [attribute](https://github.com/bridgedotnet/Bridge/wiki/attribute-reference) and [bridge.json](https://github.com/bridgedotnet/Bridge/wiki/global-configuration) docs for additional details.

You could take this even one step cleaner by moving the `[External]` attribute into the projects **AssemblyInfo.cs** file. I can really demo that in Deck.NET, but it would look like the following:

https://deck.net/e23ce93ded8e881a9c2e29ac9360b193

```csharp
using System;
using Bridge;

// Move the following line into AssemblyInfo.cs
[assembly: Bridge.External]

namespace mint
{
    public static class console
    {
        public extern static void init();
        public extern static void exit();
        public extern static void clear();
        public extern static void print(string Contents = "");
        public extern static void println(string Contents = "");
    }
}
```

Hope this helps.

**Comment by XorTroll** [comment]
Great, nice to see that.
Will look into this improvement ASAP, Bridge.NET is really awesome for this stuff...

If only I could override C# built-ins like Console.WriteLine(...) with my own implementations...

Anyway, not a major issue. Thanks your your help.

**Comment by XorTroll** [comment]
Used it in latest commits, really simplifies it (didn't use the assembly attribute as it seemed to make build fail or something, but using it independently on each component works fine)
